version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mcp-atlassian:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    container_name: mcp-atlassian
    env_file:
      - ./adk-app/.env
    ports:
      - "9000:9000"
    command: ["--transport", "streamable-http", "--port", "9000", "-vv"]

volumes:
  postgres_data:
    driver: local
